# Generated by Django 2.1.5 on 2019-02-18 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('budget_name', models.CharField(max_length=200)),
                ('total_budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('user_id', models.IntegerField()),
                ('budget_id', models.IntegerField()),
            ],
        ),
    ]
