# Generated by Django 2.1.5 on 2019-02-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costs',
            name='user_id',
        ),
    ]
